/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/defender.glb 
Author: PROJECT CAR90 (https://sketchfab.com/samuelcarvalho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/land-rover-defender-edition-grasmere-green-b7596dc0abc749c3b076d1f830715a54
Title: Land Rover Defender - Edition Grasmere Green
*/

